name: module_wan_flutter
description: 玩android客户端flutter版

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  dio_cookie_manager: 1.0.0
  cookie_jar: ^1.0.0
  logger: any
  flutter_swiper: ^1.1.6
  #Json解析
  json_annotation: ^3.1.1


  #cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.6
  json_serializable: ^3.5.0


flutter:

  uses-material-design: true


  module:
    androidX: true
    androidPackage: com.xu.module.module_wan_flutter
    iosBundleIdentifier: com.xu.module.moduleWanFlutter
